
language: perl

matrix:
  include:
    - perl: '5.8'
      env: SKIP_XT_TESTS=1
    - perl: '5.10'
    - perl: '5.12'
    - perl: '5.14'
    - perl: '5.16'
    - perl: '5.18'
    - perl: '5.20'
    - perl: '5.22'
    - perl: '5.24'
    - perl: '5.26'

before_install:
  - export AUTOMATED_TESTING=1

install:
  - if [[ -z $SKIP_XT_TESTS ]]; then cpanm --quiet --installdeps --notest --skip-satisfied --with-develop .; fi
  - if [[ -n $SKIP_XT_TESTS ]]; then cpanm --quiet --installdeps --notest --skip-satisfied .; fi

script:
  - perl Makefile.PL && make test
  - if [[ -z $SKIP_XT_TESTS ]]; then prove -lr xt/author; fi
