---
abstract: 'sshss - Use your preferred shell and own home directory for shared SSH accounts'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Capture::Tiny: '0'
  Test::MockModule: '0'
  Test::More: '0'
  Test::TempDir::Tiny: '0'
  autodie: '0'
  perl: '5.006'
  subs: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: '0'
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150005'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-SSH-SwitchShell
no_index:
  directory:
    - corpus
    - examples
    - t
    - xt
provides:
  App::SSH::SwitchShell:
    file: bin/sshss
    version: '0.003'
requires:
  Cwd: '0'
  English: '0'
  File::Spec: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/App-SSH-SwitchShell/issues
  homepage: https://github.com/skirmess/App-SSH-SwitchShell
  repository: https://github.com/skirmess/App-SSH-SwitchShell.git
version: '0.003'
x_BuiltWith:
  modules:
    Capture::Tiny: '0.46'
    Cwd: '3.63'
    English: '1.10'
    ExtUtils::MakeMaker: '7.30'
    File::Spec: '3.63'
    Perl::Critic: '1.130'
    Perl::Critic::Policy::Moose::ProhibitDESTROYMethod: '1.05'
    Perl::Critic::Policy::Moose::ProhibitLazyBuild: '1.05'
    Perl::Critic::Policy::Moose::ProhibitMultipleWiths: '1.05'
    Perl::Critic::Policy::Moose::ProhibitNewMethod: '1.05'
    Perl::Critic::Policy::Moose::RequireCleanNamespace: '1.05'
    Perl::Critic::Policy::Moose::RequireMakeImmutable: '1.05'
    Perl::Critic::Utils: '1.130'
    Pod::Wordlist: '1.20'
    Test::CPAN::Changes: '0.400002'
    Test::CPAN::Meta: '0.25'
    Test::CPAN::Meta::JSON: '0.16'
    Test::CleanNamespaces: '0.22'
    Test::DistManifest: '1.014'
    Test::EOL: '2.00'
    Test::Kwalitee: '1.26'
    Test::MinimumVersion: '0.101082'
    Test::MockModule: '0.12'
    Test::Mojibake: '1.3'
    Test::More: '1.302096'
    Test::NoTabs: '2.00'
    Test::Perl::Critic: '1.03'
    Test::Pod: '1.51'
    Test::Pod::No404s: '0.02'
    Test::Portability::Files: '0.07'
    Test::Spelling: '0.20'
    Test::TempDir::Tiny: '0.016'
    Test::Version: '2.05'
    autodie: '2.29'
    strict: '1.11'
    subs: '1.02'
    warnings: '1.36'
  perl:
    original: v5.24.0
    qv: 1
    version:
      - 5
      - 24
      - 0
  perl-config:
    gccversion: 4.9.4
    myarchname: i86pc-solaris
    osname: solaris
  platform: solaris
  uname: 'SunOS pernaia 5.11 joyent_20170330T015208Z i86pc i386 i86pc Solaris'
x_Dist_Zilla:
  perl:
    version: '5.024000'
  plugins:
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: '0'
          check_all_prereqs: '0'
          modules:
            - Dist::Zilla::PluginBundle::Author::SKIRMESS
          phase: build
          run_under_travis: '0'
          skip: []
      name: '@Author::SKIRMESS/stale modules, build'
      version: '0.054'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: '1'
          check_all_prereqs: '1'
          modules: []
          phase: release
          run_under_travis: '0'
          skip: []
      name: '@Author::SKIRMESS/stale modules, release'
      version: '0.054'
    -
      class: Dist::Zilla::Plugin::Git::Contributors
      config:
        Dist::Zilla::Plugin::Git::Contributors:
          git_version: 2.11.0
          include_authors: '0'
          include_releaser: '1'
          order_by: name
          paths: []
      name: '@Author::SKIRMESS/Git::Contributors'
      version: '0.030'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename:
            - INSTALL
            - LICENSE
            - META.json
            - META.yml
            - Makefile.PL
            - README.md
            - cpanfile
            - dist.ini
          exclude_match: []
          follow_symlinks: '0'
          include_dotfiles: '1'
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: '0'
      name: '@Author::SKIRMESS/Git::GatherDir'
      version: '2.042'
    -
      class: Dist::Zilla::Plugin::VersionFromMainModule
      name: '@Author::SKIRMESS/VersionFromMainModule'
      version: '0.03'
    -
      class: Dist::Zilla::Plugin::ReversionOnRelease
      name: '@Author::SKIRMESS/ReversionOnRelease'
      version: '0.06'
    -
      class: Dist::Zilla::Plugin::Author::SKIRMESS::RepositoryBase
      name: '@Author::SKIRMESS/Author::SKIRMESS::RepositoryBase'
      version: '0.021'
    -
      class: Dist::Zilla::Plugin::Author::SKIRMESS::InsertVersion
      name: '@Author::SKIRMESS/Author::SKIRMESS::InsertVersion'
      version: '0.021'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::SKIRMESS/NextRelease'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - .perlcriticrc
            - .perltidyrc
            - .travis.yml
            - Changes
            - META.json
            - META.yml
            - Makefile.PL
            - README.md
            - cpanfile
            - dist.ini
            - xt/author/clean-namespaces.t
            - xt/author/critic.t
            - xt/author/minimum_version.t
            - xt/author/mojibake.t
            - xt/author/no-tabs.t
            - xt/author/pod-no404s.t
            - xt/author/pod-spell.t
            - xt/author/pod-syntax.t
            - xt/author/portability.t
            - xt/author/test-version.t
            - xt/release/changes.t
            - xt/release/distmeta.t
            - xt/release/eol.t
            - xt/release/kwalitee.t
            - xt/release/manifest.t
            - xt/release/meta-json.t
            - xt/release/meta-yaml.t
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
      name: '@Author::SKIRMESS/Git::Check'
      version: '2.042'
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: '@Author::SKIRMESS/Git::Remote::Check'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::SKIRMESS/PruneCruft'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::SKIRMESS/ManifestSkip'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::SKIRMESS/AutoPrereqs'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs::Perl::Critic
      name: '@Author::SKIRMESS/AutoPrereqs::Perl::Critic'
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::SKIRMESS/Authority'
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::SKIRMESS/MinimumPerl'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::SKIRMESS/MetaNoIndex'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::SKIRMESS/GithubMeta'
      version: '0.54'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: '@Author::SKIRMESS/ReadmeAnyFromPod'
      version: '0.163250'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::SKIRMESS/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '6.010'
          include_underscores: '0'
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002004'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000031'
          version: '0.004'
      name: '@Author::SKIRMESS/MetaProvides::Package'
      version: '2.004003'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder:
            - ':ExecFiles'
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: ':ExecFiles'
              version: '6.010'
          include_underscores: '0'
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002004'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000031'
          version: '0.004'
      name: '@Author::SKIRMESS/MetaProvides::Package/ExecFiles'
      version: '2.004003'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::SKIRMESS/MetaConfig'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          $Module::Metadata::VERSION: '1.000031'
          _stash_key: x_BuiltWith
          external_file_name: misc/built_with.json
          show_config: '1'
          show_uname: '1'
          uname:
            uname_args:
              - -a
            uname_call: uname
          use_external_file: ~
      name: '@Author::SKIRMESS/MetaData::BuiltWith'
      version: '1.004005'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::SKIRMESS/MetaYAML'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::SKIRMESS/MetaJSON'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::CPANFile
      name: '@Author::SKIRMESS/CPANFile'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: '@Author::SKIRMESS/ReadmeAnyFromPod/ReadmeTextInBuild'
      version: '0.163250'
    -
      class: Dist::Zilla::Plugin::CopyrightYearFromGit
      name: '@Author::SKIRMESS/CopyrightYearFromGit'
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::SKIRMESS/License'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::SKIRMESS/InstallGuide'
      version: '1.200007'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::SKIRMESS/ExecDir'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::SKIRMESS/ShareDir'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '1'
      name: '@Author::SKIRMESS/MakeMaker'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::SKIRMESS/Manifest'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::SKIRMESS/CopyFilesFromBuild'
      version: '0.170880'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      config:
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
      name: '@Author::SKIRMESS/Git::CheckFor::CorrectBranch'
      version: '0.014'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      config:
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
      name: '@Author::SKIRMESS/Git::CheckFor::MergeConflicts'
      version: '0.014'
    -
      class: Dist::Zilla::Plugin::CheckMetaResources
      name: '@Author::SKIRMESS/CheckMetaResources'
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::SKIRMESS/CheckPrereqsIndexed'
      version: '0.020'
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@Author::SKIRMESS/CheckChangesHasContent'
      version: '0.010'
    -
      class: Dist::Zilla::Plugin::CheckSelfDependency
      config:
        Dist::Zilla::Plugin::CheckSelfDependency:
          finder:
            - ':InstallModules'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000031'
          version: '0.004'
      name: '@Author::SKIRMESS/CheckSelfDependency'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::CheckStrictVersion
      name: '@Author::SKIRMESS/CheckStrictVersion'
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '1'
      name: '@Author::SKIRMESS/RunExtraTests'
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::SKIRMESS/TestRelease'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::CheckIssues
      name: '@Author::SKIRMESS/CheckIssues'
      version: '0.010'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::SKIRMESS/ConfirmRelease'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::SKIRMESS/UploadToCPAN'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromRelease
      config:
        Dist::Zilla::Plugin::CopyFilesFromRelease:
          filename: []
          match:
            - .pm$
            - ^bin/
      name: '@Author::SKIRMESS/CopyFilesFromRelease'
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: '%v'
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - .perlcriticrc
            - .perltidyrc
            - .travis.yml
            - Changes
            - INSTALL
            - LICENSE
            - META.json
            - META.yml
            - Makefile.PL
            - README.md
            - cpanfile
            - dist.ini
            - xt/author/clean-namespaces.t
            - xt/author/critic.t
            - xt/author/minimum_version.t
            - xt/author/mojibake.t
            - xt/author/no-tabs.t
            - xt/author/pod-no404s.t
            - xt/author/pod-spell.t
            - xt/author/pod-syntax.t
            - xt/author/portability.t
            - xt/author/test-version.t
            - xt/release/changes.t
            - xt/release/distmeta.t
            - xt/release/eol.t
            - xt/release/kwalitee.t
            - xt/release/manifest.t
            - xt/release/meta-json.t
            - xt/release/meta-yaml.t
          allow_dirty_match:
            - (?^:\.pm$)
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::SKIRMESS/Git::Commit'
      version: '2.042'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: '0'
          tag: '0.003'
          tag_format: '%v'
          tag_message: ''
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::SKIRMESS/Git::Tag'
      version: '2.042'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: '1'
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
      name: '@Author::SKIRMESS/Git::Push'
      version: '2.042'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::VerifyPhases
      name: '@Author::SKIRMESS/VerifyPhases'
      version: '0.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::SKIRMESS/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '6.010'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.010'
x_authority: cpan:SKIRMESS
x_serialization_backend: 'YAML::Tiny version 1.70'
