---
abstract: 'sshss - Use your preferred shell and own home directory for shared SSH accounts'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Capture::Tiny: '0'
  Test::MockModule: '0'
  Test::More: '0'
  Test::TempDir::Tiny: '0'
  autodie: '0'
  lib: '0'
  perl: '5.006'
  subs: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150005'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-SSH-SwitchShell
no_index:
  directory:
    - corpus
    - dzil-inc
    - examples
    - inc
    - t
    - xt
provides:
  App::SSH::SwitchShell:
    file: bin/sshss
    version: '0.005'
requires:
  Cwd: '0'
  English: '0'
  File::Spec: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/App-SSH-SwitchShell/issues
  homepage: https://github.com/skirmess/App-SSH-SwitchShell
  repository: https://github.com/skirmess/App-SSH-SwitchShell.git
version: '0.005'
x_Dist_Zilla:
  perl:
    version: '5.024000'
  plugins:
    -
      class: Dist::Zilla::Plugin::lib
      config:
        Dist::Zilla::Plugin::lib:
          lib:
            - dzil-inc/lib
      name: lib
      version: '0.001002'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 0
          check_all_prereqs: 0
          modules:
            - MyBundle
          phase: build
          run_under_travis: 0
          skip: []
      name: '=MyBundle/stale modules, build'
      version: '0.054'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 1
          check_all_prereqs: 1
          modules: []
          phase: release
          run_under_travis: 0
          skip: []
      name: '=MyBundle/stale modules, release'
      version: '0.054'
    -
      class: Dist::Zilla::Plugin::Git::Contributors
      config:
        Dist::Zilla::Plugin::Git::Contributors:
          git_version: 2.11.0
          include_authors: 0
          include_releaser: 1
          order_by: name
          paths: []
      name: =MyBundle/Git::Contributors
      version: '0.032'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename:
            - INSTALL
            - LICENSE
            - META.json
            - META.yml
            - Makefile.PL
            - README.md
            - cpanfile
            - dist.ini
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 1
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: 0
      name: =MyBundle/Git::GatherDir
      version: '2.043'
    -
      class: Dist::Zilla::Plugin::VersionFromMainModule
      name: =MyBundle/VersionFromMainModule
      version: '0.03'
    -
      class: Dist::Zilla::Plugin::ReversionOnRelease
      name: =MyBundle/ReversionOnRelease
      version: '0.06'
    -
      class: MyRepositoryBase
      name: =MyBundle/=MyRepositoryBase
      version: '0.033'
    -
      class: MyInsertVersion
      name: =MyBundle/=MyInsertVersion
      version: '0.033'
    -
      class: Dist::Zilla::Plugin::Git::FilePermissions
      name: =MyBundle/Git::FilePermissions
      version: '0.004'
    -
      class: Dist::Zilla::Plugin::Git::RequireUnixEOL
      name: =MyBundle/Git::RequireUnixEOL
      version: '0.002'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: =MyBundle/NextRelease
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - .appveyor.yml
            - .perltidyrc
            - .travis.yml
            - Changes
            - META.json
            - META.yml
            - Makefile.PL
            - README.md
            - cpanfile
            - dist.ini
            - t/00-load.t
            - xt/author/clean-namespaces.t
            - xt/author/minimum_version.t
            - xt/author/mojibake.t
            - xt/author/no-tabs.t
            - xt/author/perlcritic-code.t
            - xt/author/perlcritic-tests.t
            - xt/author/perlcriticrc-code
            - xt/author/perlcriticrc-tests
            - xt/author/pod-no404s.t
            - xt/author/pod-spell.t
            - xt/author/pod-syntax.t
            - xt/author/portability.t
            - xt/author/test-version.t
            - xt/release/changes.t
            - xt/release/distmeta.t
            - xt/release/eol.t
            - xt/release/kwalitee.t
            - xt/release/manifest.t
            - xt/release/meta-json.t
            - xt/release/meta-yaml.t
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
      name: =MyBundle/Git::Check
      version: '2.043'
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: =MyBundle/Git::Remote::Check
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: =MyBundle/PruneCruft
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: =MyBundle/ManifestSkip
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: =MyBundle/AutoPrereqs
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs::Perl::Critic
      name: '=MyBundle/AutoPrereqs::Perl::Critic / code'
      version: '0.005'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs::Perl::Critic
      name: '=MyBundle/AutoPrereqs::Perl::Critic / tests'
      version: '0.005'
    -
      class: Dist::Zilla::Plugin::Authority
      name: =MyBundle/Authority
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: =MyBundle/MinimumPerl
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: =MyBundle/MetaNoIndex
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: =MyBundle/GithubMeta
      version: '0.54'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: =MyBundle/ReadmeAnyFromPod
      version: '0.163250'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: =MyBundle/MetaProvides::Package/AUTOVIV/:InstallModulesPM
              version: '6.010'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002004'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000031'
          version: '0.004'
      name: =MyBundle/MetaProvides::Package
      version: '2.004003'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder:
            - ':ExecFiles'
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: ':ExecFiles'
              version: '6.010'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002004'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000031'
          version: '0.004'
      name: =MyBundle/MetaProvides::Package/ExecFiles
      version: '2.004003'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: =MyBundle/MetaConfig
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: =MyBundle/MetaYAML
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: =MyBundle/MetaJSON
      version: '6.010'
    -
      class: MyCPANFile
      name: =MyBundle/=MyCPANFile
      version: '0.033'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: =MyBundle/ReadmeAnyFromPod/ReadmeTextInBuild
      version: '0.163250'
    -
      class: Dist::Zilla::Plugin::License
      name: =MyBundle/License
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: =MyBundle/InstallGuide
      version: '1.200007'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: =MyBundle/ExecDir
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: =MyBundle/ShareDir
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: =MyBundle/MakeMaker
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: =MyBundle/Manifest
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: =MyBundle/CopyFilesFromBuild
      version: '0.170880'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      config:
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
      name: =MyBundle/Git::CheckFor::CorrectBranch
      version: '0.014'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      config:
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
      name: =MyBundle/Git::CheckFor::MergeConflicts
      version: '0.014'
    -
      class: Dist::Zilla::Plugin::CheckMetaResources
      name: =MyBundle/CheckMetaResources
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: =MyBundle/CheckPrereqsIndexed
      version: '0.020'
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: =MyBundle/CheckChangesHasContent
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::CheckSelfDependency
      config:
        Dist::Zilla::Plugin::CheckSelfDependency:
          finder:
            - ':InstallModules'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000031'
          version: '0.004'
      name: =MyBundle/CheckSelfDependency
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::CheckStrictVersion
      name: =MyBundle/CheckStrictVersion
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: =MyBundle/RunExtraTests
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: =MyBundle/TestRelease
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::CheckIssues
      name: =MyBundle/CheckIssues
      version: '0.010'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: =MyBundle/ConfirmRelease
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: =MyBundle/UploadToCPAN
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromRelease
      config:
        Dist::Zilla::Plugin::CopyFilesFromRelease:
          filename: []
          match:
            - \.pm$
            - ^bin/
      name: =MyBundle/CopyFilesFromRelease
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: '%v'
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - .appveyor.yml
            - .perltidyrc
            - .travis.yml
            - Changes
            - INSTALL
            - LICENSE
            - META.json
            - META.yml
            - Makefile.PL
            - README.md
            - cpanfile
            - dist.ini
            - t/00-load.t
            - xt/author/clean-namespaces.t
            - xt/author/minimum_version.t
            - xt/author/mojibake.t
            - xt/author/no-tabs.t
            - xt/author/perlcritic-code.t
            - xt/author/perlcritic-tests.t
            - xt/author/perlcriticrc-code
            - xt/author/perlcriticrc-tests
            - xt/author/pod-no404s.t
            - xt/author/pod-spell.t
            - xt/author/pod-syntax.t
            - xt/author/portability.t
            - xt/author/test-version.t
            - xt/release/changes.t
            - xt/release/distmeta.t
            - xt/release/eol.t
            - xt/release/kwalitee.t
            - xt/release/manifest.t
            - xt/release/meta-json.t
            - xt/release/meta-yaml.t
          allow_dirty_match:
            - (?^:\.pm$)
            - (?^:^bin/)
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: =MyBundle/Git::Commit
      version: '2.043'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: 0
          tag: '0.005'
          tag_format: '%v'
          tag_message: ''
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: =MyBundle/Git::Tag
      version: '2.043'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.11.0
          repo_root: .
      name: =MyBundle/Git::Push
      version: '2.043'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.010'
    -
      class: Dist::Zilla::Plugin::VerifyPhases
      name: =MyBundle/VerifyPhases
      version: '0.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: =MyBundle/MetaProvides::Package/AUTOVIV/:InstallModulesPM
      version: '6.010'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.010'
x_authority: cpan:SKIRMESS
x_serialization_backend: 'YAML::Tiny version 1.70'
