---
abstract: 'sshss - Use your preferred shell and own home directory for shared SSH accounts'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Capture::Tiny: '0'
  Test::MockModule: '0'
  Test::More: '0'
  Test::TempDir::Tiny: '0'
  autodie: '0'
  lib: '0'
  perl: '5.006'
  subs: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150005'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-SSH-SwitchShell
no_index:
  directory:
    - corpus
    - dzil-inc
    - examples
    - inc
    - t
    - xt
provides:
  App::SSH::SwitchShell:
    file: bin/sshss
    version: '0.005'
requires:
  Cwd: '0'
  English: '0'
  File::Spec: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/App-SSH-SwitchShell/issues
  homepage: https://github.com/skirmess/App-SSH-SwitchShell
  repository: https://github.com/skirmess/App-SSH-SwitchShell.git
version: '0.005'
x_serialization_backend: 'YAML::Tiny version 1.70'
