#!perl

use 5.006;
use strict;
use warnings;

# generated by Dist::Zilla::Plugin::Author::SKIRMESS::RepositoryBase 0.033

use Test::Mojibake;

all_files_encoding_ok( grep { -d } qw( bin lib t xt ) );
